# Generated by Django 3.2.25 on 2024-07-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midis',
            name='centro_poblado',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='midis',
            name='departamento',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='midis',
            name='distrito',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='midis',
            name='provincia',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
