# Generated by Django 3.2.25 on 2024-07-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midis', '0002_auto_20240716_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midis',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
