services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - 5433:5432
    
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: accress
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      HOSTNAME: localhost
    # depends_on:
    #   - db
    network_mode: "host"
