# Generated by Django 3.2.25 on 2024-08-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoperu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoperu',
            old_name='departamento',
            new_name='indicador',
        ),
        migrations.RenameField(
            model_name='geoperu',
            old_name='distrito',
            new_name='poblacion',
        ),
        migrations.RenameField(
            model_name='geoperu',
            old_name='provincia',
            new_name='porcentaje',
        ),
    ]
