# Generated by Django 3.2.25 on 2024-08-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoperu', '0002_auto_20240808_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoperu',
            name='indicador',
            field=models.CharField(max_length=500),
        ),
    ]
