# Generated by Django 3.2.25 on 2024-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(blank=True, default=None, max_length=900)),
                ('provincia', models.CharField(blank=True, default=None, max_length=900)),
                ('distrito', models.CharField(blank=True, default=None, max_length=900)),
                ('key', models.CharField(blank=True, default=None, max_length=900)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SuSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
            ],
        ),
    ]
