# Generated by Django 3.2.25 on 2024-06-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susalud', '0002_alter_ipress_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipress',
            name='key',
            field=models.CharField(max_length=900),
        ),
    ]
