# Generated by Django 3.2.25 on 2024-07-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susalud', '0003_alter_ipress_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipress',
            name='departamento',
            field=models.CharField(blank=True, default=None, max_length=900),
        ),
        migrations.AddField(
            model_name='ipress',
            name='distrito',
            field=models.CharField(blank=True, default=None, max_length=900),
        ),
        migrations.AddField(
            model_name='ipress',
            name='provincia',
            field=models.CharField(blank=True, default=None, max_length=900),
        ),
        migrations.AlterField(
            model_name='ipress',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=900),
        ),
    ]
