# Generated by Django 3.2.25 on 2024-05-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pea2017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pea_ocupada', models.CharField(max_length=100)),
                ('pea_desocupada', models.CharField(max_length=100)),
                ('no_pea', models.CharField(max_length=100)),
            ],
        ),
    ]
