# Generated by Django 3.2.25 on 2024-06-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea2017', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pea2017',
            old_name='codigo',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='pea2017',
            name='no_pea',
        ),
        migrations.RemoveField(
            model_name='pea2017',
            name='pea_desocupada',
        ),
        migrations.RemoveField(
            model_name='pea2017',
            name='pea_ocupada',
        ),
        migrations.AddField(
            model_name='pea2017',
            name='distrito',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pea2017',
            name='provincia',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
