# Generated by Django 3.2.25 on 2024-06-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea2017', '0002_auto_20240625_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pea2017',
            name='distrito',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pea2017',
            name='provincia',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
