# Generated by Django 3.2.25 on 2024-07-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('casos', models.IntegerField()),
                ('porcentaje', models.FloatField()),
            ],
        ),
    ]
