# Generated by Django 3.2.25 on 2024-07-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minedu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(blank=True, default=None, max_length=100)),
                ('provincia', models.CharField(blank=True, default=None, max_length=100)),
                ('distrito', models.CharField(blank=True, default=None, max_length=100)),
                ('nombre', models.CharField(blank=True, default=None, max_length=100)),
                ('niveles', models.JSONField(blank=True, default=None)),
            ],
        ),
    ]
