# Generated by Django 3.2.25 on 2024-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='-', max_length=100)),
                ('provincia', models.CharField(default='-', max_length=100)),
                ('distrito', models.CharField(default='-', max_length=100)),
                ('key', models.CharField(default='-', max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pubinei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='-', max_length=100)),
                ('provincia', models.CharField(default='-', max_length=100)),
                ('distrito', models.CharField(default='-', max_length=100)),
                ('nombre', models.CharField(default='-', max_length=100)),
                ('casos', models.IntegerField(default=0)),
                ('porcentaje', models.FloatField(default=0.0)),
            ],
        ),
    ]
