# Generated by Django 3.2.25 on 2024-07-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubinei', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubinei',
            name='key',
        ),
        migrations.RemoveField(
            model_name='pubinei',
            name='value',
        ),
        migrations.AddField(
            model_name='pubinei',
            name='casos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pubinei',
            name='departamento',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pubinei',
            name='distrito',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pubinei',
            name='nombre',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pubinei',
            name='porcentaje',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pubinei',
            name='provincia',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
