# Generated by Django 3.2.25 on 2024-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubinei', '0002_auto_20240715_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='-', max_length=100)),
                ('provincia', models.CharField(default='-', max_length=100)),
                ('distrito', models.CharField(default='-', max_length=100)),
                ('key', models.CharField(default='-', max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
