# Generated by Django 3.2.25 on 2024-08-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubinei', '0002_alter_poblacion_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='poblacion',
            name='idccpp',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
